### ISSUE TITLE
R-build function definitions removed

### ISSUE THREAD

**Issue by JustBob81** [jcrodriguez1989/renv-installer#1]
Line 512 in R-build refers to use_xcode_sdk_zlib and use_homebrew_zlib. The definitions for these were removed in commit 775e99a. Installing R appears to work with the original function definitions returned. However, if these were intended to be removed then the referenced on 512 should be removed.

Exciting project, thanks!

**Comment by jcrodriguez1989** [comment]
Thanks for this observation! 👏

**Comment by jcrodriguez1989** [comment]
Please, try out the last version.
thanks to @sjwmoveon .
